### ISSUE TITLE
Cyrillic Support

### ISSUE THREAD

**Issue by KERRAT** [Noisrev/Noisrev.League.IO.RST#8]
During my work, I have encountered a problem that seems to arise specifically when the ComputeOffset function deals with Cyrillic characters. The problem is an overflow of the uint64 value.

Main aim of my work: make custom (mod) `ukrainian` translation for EUW/EUNE servers of in-game text.

**To Reproduce**
Go to my fork: https://github.com/KERRAT/Noisrev.League.IO.RST/tree/ukr_support

Or use this steps to reproduce the behavior:
1. Get ru-version of stringtable
[main_ru_ru.zip](https://github.com/Wenveo/Noisrev.League.IO.RST/files/12109155/main_ru_ru.zip)

add it to ItemGroup and into Resources folder 
```    
   <ItemGroup>
      <None Update="Resources\fontconfig_en_us.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Resources\main_ru_ru.stringtable">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
```
2. separate writing and reading tests (the problem only in writing, reading works fine)

**RSTTest.cs**
```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;
using System;
using System.IO;
using System.Text;

namespace Noisrev.League.IO.RST.Test
{
    [SimpleJob(RuntimeMoniker.Net461)]
    [MemoryDiagnoser]
    [RPlotExporter]
    [RankColumn]
    public class RSTReadTest
    {
        private readonly string en_us = Path.Combine("Resources", "main_ru_ru.stringtable");
        private RSTFile InputRSTFile;

        [GlobalSetup]
        public void Setup()
        {
            InputRSTFile = new RSTFile(File.OpenRead(en_us), false);
        }

        [Benchmark]
        public void Open()
        {
            InputRSTFile = new RSTFile(File.OpenRead(en_us), false);
        }
    }

    [SimpleJob(RuntimeMoniker.Net461)]
    [MemoryDiagnoser]
    [RPlotExporter]
    [RankColumn]
    public class RSTWriteTest
    {
        public readonly string en_us = Path.Combine("Resources", "main_ru_ru.stringtable");
        public readonly string output = Path.Combine("Resources", "main_ru_ru_output.stringtable");
        public RSTFile InputRSTFile;

        [GlobalSetup]
        public void Setup()
        {
            InputRSTFile = new RSTFile(File.OpenRead(en_us), false);
        }

        [Benchmark]
        public void Write()
        {
            InputRSTFile.Write(File.Create(output), false);
        }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            Console.OutputEncoding = Encoding.UTF8;
            //BenchmarkRunner.Run<RSTReadTest>();
            BenchmarkRunner.Run<RSTWriteTest>();
        }
    }
}
```

3. Add logging to see issue

**OffsetHelper.cs**
```
    public static ulong ComputeOffset(this long offset, RType type)
    {
        Console.WriteLine(offset << (byte)type);
        return Convert.ToUInt64(offset << (byte)type);
    }
```

**RSTFile.cs**,     public void Write(Stream outputStream, bool leaveOpen)
```
foreach (var entry in Entries)
        {
            var text = entry.Value;

            // Try to get a string from the dictionary.
            // If false, add the current string and write the current string to the data block.
            if (!textOffsets.TryGetValue(text, out var offset))
            {
                // Current offset
                offset = dataWriter.Position;

                // Write the Text
                dataWriter.Write(text, Encoding.UTF8, true);

                // Add the text and offset to the Dictionary
                textOffsets.Add(text, offset);
            }

            try
            {
                // Write the Hash
                bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type));
            }catch(Exception ex)
            {
                Console.OutputEncoding = Encoding.UTF8;
                Console.WriteLine($"bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type)); \nError: {ex}, \ntext: {text}, \noffset: {offset}");
            }
```

After running a writing test for a few seconds, the value of offset << (byte)type exceeds a certain limit and becomes negative. Consequently, conversion to uint64 becomes impossible and System.OverflowException: Value was either too large or too small for a UInt64 appears

Part of logs:
```
1451905104478208
-9145542006771023872
bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type));
Error: System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int64 value)
   at Noisrev.League.IO.RST.RSTFile.Write(Stream outputStream, Boolean leaveOpen),
text: Герб Шуримы,
offset: 16918788
5508798996006567936
2813309406874173440
-9145529912143118336
bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type));
Error: System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int64 value)
   at Noisrev.League.IO.RST.RSTFile.Write(Stream outputStream, Boolean leaveOpen),
text: Энергия на 18 уровне,
offset: 16918810
1451905104478208
-9145510120933818368
bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type));
Error: System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int64 value)
   at Noisrev.League.IO.RST.RSTFile.Write(Stream outputStream, Boolean leaveOpen),
text: Фиолетовый осадный наездник,
offset: 16918846
-9145480983875682304
bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type));
Error: System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int64 value)
   at Noisrev.League.IO.RST.RSTFile.Write(Stream outputStream, Boolean leaveOpen),
text: ЧМ-2019: GAM,
offset: 16918899
-9145472737538473984
bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type));
Error: System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int64 value)
   at Noisrev.League.IO.RST.RSTFile.Write(Stream outputStream, Boolean leaveOpen),
text: <titleLeft>Искупление</titleLeft><titleRight>Цена продажи: <gold>@Value@</gold></titleRight><subtitleLeft><attention>%i:scaleHealth% @FlatHPPoolMod@</attention> здоровья<br><attention>%i:scaleManaRegen% @PercentBaseMPRegenMod*100@%</attention> базового восстановления маны<br><attention>%i:scaleHealShield% @PercentHealingAmountMod*100@%</attention> эффективности лечения и щитов</subtitleLeft><mainText>{{ Item_Passive_List }}<li><passive>Гармония:</passive> увеличивает базовое восстановление здоровья на @HPRegenIncrease*100@% за каждые дополнительные <scalemana>@BaseManaRegen*100@% базового восстановления маны</scalemana>.<br><br><rules>Предмет можно активировать после смерти. Урон и лечение уменьшаются на @DiminishedEffect*100@%, если недавно к цели было применено другое <active>Вмешательство</active>. {{ Item_Ally_Scaling }}</rules></mainText>,
offset: 16918914
-9144844366643200000
bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type));
Error: System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int64 value)
   at Noisrev.League.IO.RST.RSTFile.Write(Stream outputStream, Boolean leaveOpen),
text: Иконка ''Пчела Синджед'',
offset: 16920057
-9144820727143202816
bytesWriter.Write(RSTHash.ComputeHash(entry.Key, offset, Type));
Error: System.OverflowException: Value was either too large or too small for a UInt64.
   at System.Convert.ToUInt64(Int64 value)
   at Noisrev.League.IO.RST.RSTFile.Write(Stream outputStream, Boolean leaveOpen),
text: Алмаз,
offset: 16920100
2566415720124514304
-9144814679829250048
```

**Expected behavior**
Cyrillic Support

**Comment by KERRAT** [comment]
Rion as well gives the same issue on writing back to .stringtable

![image](https://github.com/Wenveo/Noisrev.League.IO.RST/assets/70696653/415650df-a3bf-4300-b750-1d92053d13b8)

**Comment by Wenveo** [comment]
@KERRAT Sorry to see you’re hitting an issue here. This error was expected, but I didn't expect it to come so soon...

> After running a writing test for a few seconds, the value of offset << (byte)type exceeds a certain limit and becomes negative. Consequently, conversion to uint64 becomes impossible and System.OverflowException: Value was either too large or too small for a UInt64 appears

The maximum offset accepted for bit shift operation is **16777216** (<< **39** bits).
But I see that the file you uploaded has a larger offset of **19138658**, which doesn't seem to make sense.

For now, there are some problems with the offsets generated by the "**ComputeOffset**" method. 🤔

**Comment by Wenveo** [comment]
> The maximum offset accepted for bit shift operation is 16777216 (<< 39 bits).
> But I see that the file you uploaded has a larger offset of 19138658, which doesn't seem to make sense.

I seem to have made a silly mistake...
This problem can be solved by explicit conversion the offset argument in the method to **ulong**... 😅
~return Convert.ToUInt64(offset << (byte)type);~
``` CSharp
public static ulong ComputeOffset(this long offset, RType type)
{
    return (ulong)offset << (byte)type;
}
```

![image](https://github.com/Wenveo/Noisrev.League.IO.RST/assets/62750690/23b70ed0-3d1f-4436-b25a-35ca4204417e)

**Comment by Wenveo** [comment]
@KERRAT  You can try it, it will work.

> ~return Convert.ToUInt64(offset << (byte)type);~
> ```cs
> public static ulong ComputeOffset(this long offset, RType type)
> {
>     return (ulong)offset << (byte)type;
> }
> ```

![image](https://github.com/Wenveo/Noisrev.League.IO.RST/assets/62750690/d87294ea-8f6f-42e7-8c89-9d85749b918c)

**Comment by KERRAT** [comment]
Nicee! I thought that it will be a hard thing to fix 😅

Thx for your work! Waiting for new version of lib

**Comment by KERRAT** [comment]
Oh, ok, I can build lib locally as well

**Comment by KERRAT** [comment]
Ok. I guess it is new issue :D 

When i change some ru letters to ukrainian, it doesn't work as expected 


```
using Noisrev.League.IO.RST;


internal class Program
{
    private static void Main(string[] args)
    {
        var rst_ru = RSTFile.Load(@"F:\data lol\data\menu\main_ru_ru.stringtable");

        var built_ru = new RSTBuilder(rst_ru);

        built_ru.ReplaceAll("г", "ґ");
        built_ru.ReplaceAll("э", "є");
        built_ru.ReplaceAll("ъ", "'");
        built_ru.ReplaceAll("и", "і");
        built_ru.ReplaceAll("ы", "ї");

        string path_ru = "F:\\Global.ru_RU.wad.client\\data\\menu\\";

        Directory.CreateDirectory(path_ru);

        built_ru.Build(path_ru + "main_ru_ru.stringtable");
    }
}

```

**Comment by KERRAT** [comment]
new issue or here?

**Comment by KERRAT** [comment]
Works FINE!
Thx!

Not the best translation, but ok :D 
![image](https://github.com/Wenveo/Noisrev.League.IO.RST/assets/70696653/a2b0783e-ea96-4e67-a8ad-a64596fe8b2d)

![image](https://github.com/Wenveo/Noisrev.League.IO.RST/assets/70696653/68de43eb-96ef-45e3-a058-2691ee5e2e55)
